# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/skysys/stitching/ui/main.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModal)
        MainWindow.resize(1920, 1080)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/home/skysys/stitching/ui/../../.designer/backup/skysysIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.QWidget = QtWidgets.QWidget(self.centralwidget)
        self.QWidget.setObjectName("QWidget")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.QWidget)
        self.horizontalLayout_8.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_8.setSpacing(5)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.Widget = QtWidgets.QWidget(self.QWidget)
        self.Widget.setObjectName("Widget")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.Widget)
        self.horizontalLayout_12.setContentsMargins(-1, -1, 9, -1)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.ci = QtWidgets.QLabel(self.Widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ci.sizePolicy().hasHeightForWidth())
        self.ci.setSizePolicy(sizePolicy)
        self.ci.setMaximumSize(QtCore.QSize(250, 40))
        self.ci.setText("")
        self.ci.setPixmap(QtGui.QPixmap("/home/skysys/stitching/ui/../../.designer/backup/skysys.png"))
        self.ci.setScaledContents(True)
        self.ci.setObjectName("ci")
        self.verticalLayout_4.addWidget(self.ci)
        self.chListLabel = QtWidgets.QLabel(self.Widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chListLabel.sizePolicy().hasHeightForWidth())
        self.chListLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(10)
        self.chListLabel.setFont(font)
        self.chListLabel.setObjectName("chListLabel")
        self.verticalLayout_4.addWidget(self.chListLabel)
        self.chTreeWidget = QtWidgets.QTreeWidget(self.Widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chTreeWidget.sizePolicy().hasHeightForWidth())
        self.chTreeWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(10)
        self.chTreeWidget.setFont(font)
        self.chTreeWidget.setObjectName("chTreeWidget")
        self.verticalLayout_4.addWidget(self.chTreeWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(160, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.addCCTVBtn = QtWidgets.QPushButton(self.Widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addCCTVBtn.sizePolicy().hasHeightForWidth())
        self.addCCTVBtn.setSizePolicy(sizePolicy)
        self.addCCTVBtn.setMinimumSize(QtCore.QSize(0, 0))
        self.addCCTVBtn.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(10)
        self.addCCTVBtn.setFont(font)
        self.addCCTVBtn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.addCCTVBtn.setObjectName("addCCTVBtn")
        self.horizontalLayout.addWidget(self.addCCTVBtn)
        self.rmvCCTVBtn = QtWidgets.QPushButton(self.Widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rmvCCTVBtn.sizePolicy().hasHeightForWidth())
        self.rmvCCTVBtn.setSizePolicy(sizePolicy)
        self.rmvCCTVBtn.setMinimumSize(QtCore.QSize(0, 0))
        self.rmvCCTVBtn.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(10)
        self.rmvCCTVBtn.setFont(font)
        self.rmvCCTVBtn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.rmvCCTVBtn.setObjectName("rmvCCTVBtn")
        self.horizontalLayout.addWidget(self.rmvCCTVBtn)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_4.addItem(spacerItem1)
        self.streamingLabel = QtWidgets.QLabel(self.Widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.streamingLabel.sizePolicy().hasHeightForWidth())
        self.streamingLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.streamingLabel.setFont(font)
        self.streamingLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.streamingLabel.setObjectName("streamingLabel")
        self.verticalLayout_4.addWidget(self.streamingLabel)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.chComboBox = QtWidgets.QComboBox(self.Widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chComboBox.sizePolicy().hasHeightForWidth())
        self.chComboBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(10)
        self.chComboBox.setFont(font)
        self.chComboBox.setObjectName("chComboBox")
        self.horizontalLayout_4.addWidget(self.chComboBox)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem4)
        self.ptzControlLabel = QtWidgets.QLabel(self.Widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ptzControlLabel.sizePolicy().hasHeightForWidth())
        self.ptzControlLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ptzControlLabel.setFont(font)
        self.ptzControlLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ptzControlLabel.setObjectName("ptzControlLabel")
        self.verticalLayout_4.addWidget(self.ptzControlLabel)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, -1, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.leftButton = QtWidgets.QPushButton(self.Widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftButton.sizePolicy().hasHeightForWidth())
        self.leftButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        self.leftButton.setFont(font)
        self.leftButton.setObjectName("leftButton")
        self.horizontalLayout_5.addWidget(self.leftButton)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.upButton = QtWidgets.QPushButton(self.Widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.upButton.sizePolicy().hasHeightForWidth())
        self.upButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        self.upButton.setFont(font)
        self.upButton.setObjectName("upButton")
        self.verticalLayout.addWidget(self.upButton)
        self.homeButton = QtWidgets.QPushButton(self.Widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.homeButton.sizePolicy().hasHeightForWidth())
        self.homeButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.homeButton.setFont(font)
        self.homeButton.setObjectName("homeButton")
        self.verticalLayout.addWidget(self.homeButton)
        self.downButton = QtWidgets.QPushButton(self.Widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.downButton.sizePolicy().hasHeightForWidth())
        self.downButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        self.downButton.setFont(font)
        self.downButton.setObjectName("downButton")
        self.verticalLayout.addWidget(self.downButton)
        self.horizontalLayout_5.addLayout(self.verticalLayout)
        self.rightButton = QtWidgets.QPushButton(self.Widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rightButton.sizePolicy().hasHeightForWidth())
        self.rightButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        self.rightButton.setFont(font)
        self.rightButton.setObjectName("rightButton")
        self.horizontalLayout_5.addWidget(self.rightButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.zoomOutButton = QtWidgets.QPushButton(self.Widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zoomOutButton.sizePolicy().hasHeightForWidth())
        self.zoomOutButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.zoomOutButton.setFont(font)
        self.zoomOutButton.setObjectName("zoomOutButton")
        self.horizontalLayout_7.addWidget(self.zoomOutButton)
        self.zoomLabel = QtWidgets.QLabel(self.Widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zoomLabel.sizePolicy().hasHeightForWidth())
        self.zoomLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.zoomLabel.setFont(font)
        self.zoomLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.zoomLabel.setObjectName("zoomLabel")
        self.horizontalLayout_7.addWidget(self.zoomLabel)
        self.zoomInButton = QtWidgets.QPushButton(self.Widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zoomInButton.sizePolicy().hasHeightForWidth())
        self.zoomInButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.zoomInButton.setFont(font)
        self.zoomInButton.setObjectName("zoomInButton")
        self.horizontalLayout_7.addWidget(self.zoomInButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem5)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.ptzButton = QtWidgets.QPushButton(self.Widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ptzButton.sizePolicy().hasHeightForWidth())
        self.ptzButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(10)
        self.ptzButton.setFont(font)
        self.ptzButton.setObjectName("ptzButton")
        self.horizontalLayout_2.addWidget(self.ptzButton)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.verticalLayout_7.addLayout(self.horizontalLayout_2)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_7.addItem(spacerItem8)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem9)
        self.chComboBox_2 = QtWidgets.QComboBox(self.Widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chComboBox_2.sizePolicy().hasHeightForWidth())
        self.chComboBox_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(10)
        self.chComboBox_2.setFont(font)
        self.chComboBox_2.setObjectName("chComboBox_2")
        self.horizontalLayout_3.addWidget(self.chComboBox_2)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem10)
        self.verticalLayout_7.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem11)
        self.restartButton = QtWidgets.QPushButton(self.Widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.restartButton.sizePolicy().hasHeightForWidth())
        self.restartButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(10)
        self.restartButton.setFont(font)
        self.restartButton.setObjectName("restartButton")
        self.horizontalLayout_6.addWidget(self.restartButton)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem12)
        self.verticalLayout_7.addLayout(self.horizontalLayout_6)
        self.verticalLayout_4.addLayout(self.verticalLayout_7)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem13)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem14)
        self.panoramaButton = QtWidgets.QPushButton(self.Widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.panoramaButton.sizePolicy().hasHeightForWidth())
        self.panoramaButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        self.panoramaButton.setFont(font)
        self.panoramaButton.setObjectName("panoramaButton")
        self.horizontalLayout_9.addWidget(self.panoramaButton)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem15)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem16)
        self.label = QtWidgets.QLabel(self.Widget)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.horizontalLayout_12.addLayout(self.verticalLayout_4)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(-1, -1, 0, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.viewLabel_8 = QtWidgets.QLabel(self.Widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.viewLabel_8.sizePolicy().hasHeightForWidth())
        self.viewLabel_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.viewLabel_8.setFont(font)
        self.viewLabel_8.setStyleSheet("background-color: rgb(91, 91, 91);color: rgb(255, 255, 255);")
        self.viewLabel_8.setAlignment(QtCore.Qt.AlignCenter)
        self.viewLabel_8.setObjectName("viewLabel_8")
        self.gridLayout.addWidget(self.viewLabel_8, 2, 1, 1, 1)
        self.viewLabel_9 = QtWidgets.QLabel(self.Widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.viewLabel_9.sizePolicy().hasHeightForWidth())
        self.viewLabel_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.viewLabel_9.setFont(font)
        self.viewLabel_9.setStyleSheet("background-color: rgb(91, 91, 91);color: rgb(255, 255, 255);")
        self.viewLabel_9.setAlignment(QtCore.Qt.AlignCenter)
        self.viewLabel_9.setObjectName("viewLabel_9")
        self.gridLayout.addWidget(self.viewLabel_9, 2, 2, 1, 1)
        self.viewLabel_4 = QtWidgets.QLabel(self.Widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.viewLabel_4.sizePolicy().hasHeightForWidth())
        self.viewLabel_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.viewLabel_4.setFont(font)
        self.viewLabel_4.setStyleSheet("background-color: rgb(91, 91, 91);color: rgb(255, 255, 255);")
        self.viewLabel_4.setAlignment(QtCore.Qt.AlignCenter)
        self.viewLabel_4.setObjectName("viewLabel_4")
        self.gridLayout.addWidget(self.viewLabel_4, 1, 0, 1, 1)
        self.viewLabel_5 = QtWidgets.QLabel(self.Widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.viewLabel_5.sizePolicy().hasHeightForWidth())
        self.viewLabel_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.viewLabel_5.setFont(font)
        self.viewLabel_5.setStyleSheet("background-color: rgb(91, 91, 91);color: rgb(255, 255, 255);")
        self.viewLabel_5.setAlignment(QtCore.Qt.AlignCenter)
        self.viewLabel_5.setObjectName("viewLabel_5")
        self.gridLayout.addWidget(self.viewLabel_5, 1, 1, 1, 1)
        self.viewLabel_6 = QtWidgets.QLabel(self.Widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.viewLabel_6.sizePolicy().hasHeightForWidth())
        self.viewLabel_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.viewLabel_6.setFont(font)
        self.viewLabel_6.setStyleSheet("background-color: rgb(91, 91, 91);color: rgb(255, 255, 255);")
        self.viewLabel_6.setAlignment(QtCore.Qt.AlignCenter)
        self.viewLabel_6.setObjectName("viewLabel_6")
        self.gridLayout.addWidget(self.viewLabel_6, 1, 2, 1, 1)
        self.viewLabel_7 = QtWidgets.QLabel(self.Widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.viewLabel_7.sizePolicy().hasHeightForWidth())
        self.viewLabel_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.viewLabel_7.setFont(font)
        self.viewLabel_7.setStyleSheet("background-color: rgb(91, 91, 91);color: rgb(255, 255, 255);")
        self.viewLabel_7.setAlignment(QtCore.Qt.AlignCenter)
        self.viewLabel_7.setObjectName("viewLabel_7")
        self.gridLayout.addWidget(self.viewLabel_7, 2, 0, 1, 1)
        self.viewLabel_1 = QtWidgets.QLabel(self.Widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.viewLabel_1.sizePolicy().hasHeightForWidth())
        self.viewLabel_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.viewLabel_1.setFont(font)
        self.viewLabel_1.setStyleSheet("background-color: rgb(91, 91, 91);color: rgb(255, 255, 255);")
        self.viewLabel_1.setAlignment(QtCore.Qt.AlignCenter)
        self.viewLabel_1.setObjectName("viewLabel_1")
        self.gridLayout.addWidget(self.viewLabel_1, 0, 0, 1, 1)
        self.viewLabel_2 = QtWidgets.QLabel(self.Widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.viewLabel_2.sizePolicy().hasHeightForWidth())
        self.viewLabel_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.viewLabel_2.setFont(font)
        self.viewLabel_2.setStyleSheet("background-color: rgb(91, 91, 91);color: rgb(255, 255, 255);")
        self.viewLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.viewLabel_2.setObjectName("viewLabel_2")
        self.gridLayout.addWidget(self.viewLabel_2, 0, 1, 1, 1)
        self.viewLabel_3 = QtWidgets.QLabel(self.Widget)
        self.viewLabel_3.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.viewLabel_3.sizePolicy().hasHeightForWidth())
        self.viewLabel_3.setSizePolicy(sizePolicy)
        self.viewLabel_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.viewLabel_3.setFont(font)
        self.viewLabel_3.setStyleSheet("background-color: rgb(91, 91, 91);color: rgb(255, 255, 255);")
        self.viewLabel_3.setAlignment(QtCore.Qt.AlignCenter)
        self.viewLabel_3.setObjectName("viewLabel_3")
        self.gridLayout.addWidget(self.viewLabel_3, 0, 2, 1, 1)
        self.viewLabel_10 = QtWidgets.QLabel(self.Widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.viewLabel_10.sizePolicy().hasHeightForWidth())
        self.viewLabel_10.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.viewLabel_10.setFont(font)
        self.viewLabel_10.setStyleSheet("background-color: rgb(91, 91, 91);color: rgb(255, 255, 255);")
        self.viewLabel_10.setAlignment(QtCore.Qt.AlignCenter)
        self.viewLabel_10.setObjectName("viewLabel_10")
        self.gridLayout.addWidget(self.viewLabel_10, 3, 0, 1, 1)
        self.viewLabel_11 = QtWidgets.QLabel(self.Widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.viewLabel_11.sizePolicy().hasHeightForWidth())
        self.viewLabel_11.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.viewLabel_11.setFont(font)
        self.viewLabel_11.setStyleSheet("background-color: rgb(91, 91, 91);color: rgb(255, 255, 255);")
        self.viewLabel_11.setAlignment(QtCore.Qt.AlignCenter)
        self.viewLabel_11.setObjectName("viewLabel_11")
        self.gridLayout.addWidget(self.viewLabel_11, 3, 1, 1, 1)
        self.viewLabel_12 = QtWidgets.QLabel(self.Widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.viewLabel_12.sizePolicy().hasHeightForWidth())
        self.viewLabel_12.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.viewLabel_12.setFont(font)
        self.viewLabel_12.setStyleSheet("background-color: rgb(91, 91, 91);color: rgb(255, 255, 255);")
        self.viewLabel_12.setAlignment(QtCore.Qt.AlignCenter)
        self.viewLabel_12.setObjectName("viewLabel_12")
        self.gridLayout.addWidget(self.viewLabel_12, 3, 2, 1, 1)
        self.horizontalLayout_12.addLayout(self.gridLayout)
        self.horizontalLayout_8.addWidget(self.Widget)
        self.verticalLayout_5.addWidget(self.QWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SKYSYS-Monitoring System"))
        self.chListLabel.setText(_translate("MainWindow", "채널 리스트"))
        self.chTreeWidget.headerItem().setText(0, _translate("MainWindow", "CCTV"))
        self.chTreeWidget.headerItem().setText(1, _translate("MainWindow", "URL"))
        self.addCCTVBtn.setText(_translate("MainWindow", "+"))
        self.rmvCCTVBtn.setText(_translate("MainWindow", "-"))
        self.streamingLabel.setText(_translate("MainWindow", "Streaming"))
        self.ptzControlLabel.setText(_translate("MainWindow", "PTZ Control"))
        self.leftButton.setText(_translate("MainWindow", "←"))
        self.upButton.setText(_translate("MainWindow", "↑"))
        self.homeButton.setText(_translate("MainWindow", "Home"))
        self.downButton.setText(_translate("MainWindow", "↓"))
        self.rightButton.setText(_translate("MainWindow", "→"))
        self.zoomOutButton.setText(_translate("MainWindow", "─"))
        self.zoomLabel.setText(_translate("MainWindow", "Zoom"))
        self.zoomInButton.setText(_translate("MainWindow", "+"))
        self.ptzButton.setText(_translate("MainWindow", "PTZ Start"))
        self.restartButton.setText(_translate("MainWindow", "ReStart"))
        self.panoramaButton.setText(_translate("MainWindow", "Panorama Start"))
        self.label.setText(_translate("MainWindow", "version 1.0"))
        self.viewLabel_8.setText(_translate("MainWindow", "No Channel"))
        self.viewLabel_9.setText(_translate("MainWindow", "No Channel"))
        self.viewLabel_4.setText(_translate("MainWindow", "No Channel"))
        self.viewLabel_5.setText(_translate("MainWindow", "No Channel"))
        self.viewLabel_6.setText(_translate("MainWindow", "No Channel"))
        self.viewLabel_7.setText(_translate("MainWindow", "No Channel"))
        self.viewLabel_1.setText(_translate("MainWindow", "No Channel"))
        self.viewLabel_2.setText(_translate("MainWindow", "No Channel"))
        self.viewLabel_3.setText(_translate("MainWindow", "No Channel"))
        self.viewLabel_10.setText(_translate("MainWindow", "No Channel"))
        self.viewLabel_11.setText(_translate("MainWindow", "No Channel"))
        self.viewLabel_12.setText(_translate("MainWindow", "No Channel"))
